/* Generated by Together */

#ifndef TPROCESS_H
#define TPROCESS_H
#include <vcl.h>
/**
 * 进程控制, 控制进程的启动, 结束.
 * 用来控制微机监测数据回放程序Transmit.exe 
 */
class TProcess
{
public:

    TProcess( const AnsiString & file, const AnsiString & param );

    virtual ~TProcess();

    bool Run();

    void Detach();
    /**
     * @output 正在运行返回true, 否则返回false 
     */
    bool IsRunning();

    void Terminate();

    AnsiString& getParam();

    void setParam(AnsiString& param);
    
	static void KillTask(const char *processName);    
private:

    DWORD m_processId;

    AnsiString m_param;

    AnsiString m_path;
};
#endif //TPROCESS_H
